// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlnfU3wzeMpsIf7zQHQ1W2Tm44lVGSNw',
    appId: '1:521739374470:web:ed990ff1ccad8c3f5a6607',
    messagingSenderId: '521739374470',
    projectId: 'chatapp-d168e',
    authDomain: 'chatapp-d168e.firebaseapp.com',
    storageBucket: 'chatapp-d168e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCWUWyXE3ZHZHCEMz7thp_UOSQqTGKGo',
    appId: '1:521739374470:android:c7d69732755022195a6607',
    messagingSenderId: '521739374470',
    projectId: 'chatapp-d168e',
    storageBucket: 'chatapp-d168e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlW8JYol3VWNxKiZLkqLnOkBQ1TOYSRk',
    appId: '1:521739374470:ios:da38ae4cd9b3753b5a6607',
    messagingSenderId: '521739374470',
    projectId: 'chatapp-d168e',
    storageBucket: 'chatapp-d168e.appspot.com',
    iosClientId: '521739374470-vtm48nai6q1ofjmdi819t59j8ibjti8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGlW8JYol3VWNxKiZLkqLnOkBQ1TOYSRk',
    appId: '1:521739374470:ios:da38ae4cd9b3753b5a6607',
    messagingSenderId: '521739374470',
    projectId: 'chatapp-d168e',
    storageBucket: 'chatapp-d168e.appspot.com',
    iosClientId: '521739374470-vtm48nai6q1ofjmdi819t59j8ibjti8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
